"""Initial schema

Revision ID: a0c4066e937f
Revises: None
Create Date: 2026-05-27 12:35:03.256898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0c4066e937f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_email', 'users', ['email'], unique=False)
    op.create_index('idx_role', 'users', ['role'], unique=False)
    op.create_index('idx_username', 'users', ['username'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('api_activity_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('endpoint', sa.String(length=255), nullable=True),
    sa.Column('method', sa.String(length=10), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('request_data', sa.JSON(), nullable=True),
    sa.Column('response_data', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_api_act_endpoint', 'api_activity_log', ['endpoint'], unique=False)
    op.create_index('idx_api_act_timestamp', 'api_activity_log', ['timestamp'], unique=False)
    op.create_index('idx_api_act_user_id', 'api_activity_log', ['user_id'], unique=False)
    op.create_index(op.f('ix_api_activity_log_endpoint'), 'api_activity_log', ['endpoint'], unique=False)
    op.create_index(op.f('ix_api_activity_log_id'), 'api_activity_log', ['id'], unique=False)
    op.create_index(op.f('ix_api_activity_log_timestamp'), 'api_activity_log', ['timestamp'], unique=False)
    op.create_index(op.f('ix_api_activity_log_user_id'), 'api_activity_log', ['user_id'], unique=False)
    op.create_table('applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.String(length=50), nullable=False),
    sa.Column('citizen_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('quality_score', sa.Integer(), nullable=True),
    sa.Column('extraction_confidence', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('applicant_name', sa.String(length=255), nullable=True),
    sa.Column('applicant_email', sa.String(length=255), nullable=True),
    sa.Column('applicant_phone', sa.String(length=20), nullable=True),
    sa.Column('applicant_address_line1', sa.String(length=255), nullable=True),
    sa.Column('applicant_address_line2', sa.String(length=255), nullable=True),
    sa.Column('applicant_address_city', sa.String(length=100), nullable=True),
    sa.Column('applicant_address_state', sa.String(length=100), nullable=True),
    sa.Column('applicant_address_zip', sa.String(length=20), nullable=True),
    sa.Column('applicant_id_type', sa.String(length=50), nullable=True),
    sa.Column('applicant_id_number', sa.String(length=100), nullable=True),
    sa.Column('property_address_line1', sa.String(length=255), nullable=True),
    sa.Column('property_address_line2', sa.String(length=255), nullable=True),
    sa.Column('property_address_city', sa.String(length=100), nullable=True),
    sa.Column('property_address_state', sa.String(length=100), nullable=True),
    sa.Column('property_address_zip', sa.String(length=20), nullable=True),
    sa.Column('property_ward_number', sa.String(length=20), nullable=True),
    sa.Column('property_size', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('property_size_unit', sa.String(length=20), nullable=True),
    sa.Column('property_current_use', sa.String(length=100), nullable=True),
    sa.Column('property_proposed_use', sa.String(length=100), nullable=True),
    sa.Column('property_ownership_type', sa.String(length=50), nullable=True),
    sa.Column('permit_type', sa.String(length=50), nullable=False),
    sa.Column('project_description', sa.Text(), nullable=True),
    sa.Column('project_scope', sa.String(length=255), nullable=True),
    sa.Column('estimated_cost', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('estimated_cost_currency', sa.String(length=10), nullable=True),
    sa.Column('construction_area', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('construction_area_unit', sa.String(length=20), nullable=True),
    sa.Column('project_start_date', sa.Date(), nullable=True),
    sa.Column('project_end_date', sa.Date(), nullable=True),
    sa.Column('contractor_name', sa.String(length=255), nullable=True),
    sa.Column('contractor_license_number', sa.String(length=100), nullable=True),
    sa.Column('contractor_phone', sa.String(length=20), nullable=True),
    sa.Column('contractor_email', sa.String(length=255), nullable=True),
    sa.Column('contractor_address', sa.Text(), nullable=True),
    sa.Column('engineer_name', sa.String(length=255), nullable=True),
    sa.Column('engineer_license_number', sa.String(length=100), nullable=True),
    sa.Column('architect_name', sa.String(length=255), nullable=True),
    sa.Column('architect_license_number', sa.String(length=100), nullable=True),
    sa.Column('original_file_name', sa.String(length=255), nullable=True),
    sa.Column('original_file_path', sa.String(length=500), nullable=True),
    sa.Column('original_file_size', sa.Integer(), nullable=True),
    sa.Column('original_file_type', sa.String(length=50), nullable=True),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('extraction_method', sa.String(length=50), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('received_at', sa.DateTime(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.Column('assigned_to_user_id', sa.Integer(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.Column('rejected_reason', sa.Text(), nullable=True),
    sa.Column('rejection_details', sa.JSON(), nullable=True),
    sa.Column('approval_notes', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['citizen_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_application_id', 'applications', ['application_id'], unique=False)
    op.create_index('idx_assigned_to', 'applications', ['assigned_to_user_id'], unique=False)
    op.create_index('idx_citizen_id', 'applications', ['citizen_id'], unique=False)
    op.create_index('idx_city', 'applications', ['city'], unique=False)
    op.create_index('idx_created_at', 'applications', ['created_at'], unique=False)
    op.create_index('idx_permit_type', 'applications', ['permit_type'], unique=False)
    op.create_index('idx_quality_score', 'applications', ['quality_score'], unique=False)
    op.create_index('idx_status', 'applications', ['status'], unique=False)
    op.create_index('idx_submitted_at', 'applications', ['submitted_at'], unique=False)
    op.create_index(op.f('ix_applications_application_id'), 'applications', ['application_id'], unique=True)
    op.create_index(op.f('ix_applications_assigned_to_user_id'), 'applications', ['assigned_to_user_id'], unique=False)
    op.create_index(op.f('ix_applications_citizen_id'), 'applications', ['citizen_id'], unique=False)
    op.create_index(op.f('ix_applications_city'), 'applications', ['city'], unique=False)
    op.create_index(op.f('ix_applications_id'), 'applications', ['id'], unique=False)
    op.create_index(op.f('ix_applications_permit_type'), 'applications', ['permit_type'], unique=False)
    op.create_index(op.f('ix_applications_quality_score'), 'applications', ['quality_score'], unique=False)
    op.create_index(op.f('ix_applications_status'), 'applications', ['status'], unique=False)
    op.create_index(op.f('ix_applications_submitted_at'), 'applications', ['submitted_at'], unique=False)
    op.create_table('configuration',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('value_type', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_configurable', sa.Boolean(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_config_key', 'configuration', ['key'], unique=False)
    op.create_index(op.f('ix_configuration_id'), 'configuration', ['id'], unique=False)
    op.create_index(op.f('ix_configuration_key'), 'configuration', ['key'], unique=True)
    op.create_table('user_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('access_token', sa.String(length=500), nullable=False),
    sa.Column('refresh_token', sa.String(length=500), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('refresh_token')
    )
    op.create_index('idx_access_token', 'user_sessions', ['access_token'], unique=False)
    op.create_index('idx_user_id', 'user_sessions', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_sessions_access_token'), 'user_sessions', ['access_token'], unique=True)
    op.create_index(op.f('ix_user_sessions_id'), 'user_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_user_sessions_user_id'), 'user_sessions', ['user_id'], unique=False)
    op.create_table('application_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.String(length=100), nullable=True),
    sa.Column('document_name', sa.String(length=255), nullable=True),
    sa.Column('document_path', sa.String(length=500), nullable=True),
    sa.Column('document_size', sa.Integer(), nullable=True),
    sa.Column('is_required', sa.Boolean(), nullable=True),
    sa.Column('is_present', sa.Boolean(), nullable=True),
    sa.Column('is_valid', sa.Boolean(), nullable=True),
    sa.Column('validation_error', sa.Text(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_doc_application_id', 'application_documents', ['application_id'], unique=False)
    op.create_index(op.f('ix_application_documents_application_id'), 'application_documents', ['application_id'], unique=False)
    op.create_index(op.f('ix_application_documents_id'), 'application_documents', ['id'], unique=False)
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('action_category', sa.String(length=50), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_action', 'audit_log', ['action'], unique=False)
    op.create_index('idx_audit_application_id', 'audit_log', ['application_id'], unique=False)
    op.create_index('idx_audit_timestamp', 'audit_log', ['timestamp'], unique=False)
    op.create_index('idx_audit_user_id', 'audit_log', ['user_id'], unique=False)
    op.create_index(op.f('ix_audit_log_action'), 'audit_log', ['action'], unique=False)
    op.create_index(op.f('ix_audit_log_application_id'), 'audit_log', ['application_id'], unique=False)
    op.create_index(op.f('ix_audit_log_id'), 'audit_log', ['id'], unique=False)
    op.create_index(op.f('ix_audit_log_timestamp'), 'audit_log', ['timestamp'], unique=False)
    op.create_index(op.f('ix_audit_log_user_id'), 'audit_log', ['user_id'], unique=False)
    op.create_table('fraud_indicators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('indicator_type', sa.String(length=100), nullable=True),
    sa.Column('indicator_description', sa.Text(), nullable=True),
    sa.Column('risk_score', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('risk_level', sa.String(length=50), nullable=True),
    sa.Column('recommendation', sa.String(length=255), nullable=True),
    sa.Column('detected_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_fraud_application_id', 'fraud_indicators', ['application_id'], unique=False)
    op.create_index('idx_fraud_risk_level', 'fraud_indicators', ['risk_level'], unique=False)
    op.create_index(op.f('ix_fraud_indicators_application_id'), 'fraud_indicators', ['application_id'], unique=False)
    op.create_index(op.f('ix_fraud_indicators_id'), 'fraud_indicators', ['id'], unique=False)
    op.create_table('queue_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('queue_name', sa.String(length=100), nullable=False),
    sa.Column('queue_priority', sa.String(length=50), nullable=True),
    sa.Column('assigned_to_user_id', sa.Integer(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('completed_by_user_id', sa.Integer(), nullable=True),
    sa.Column('estimated_completion_time', sa.DateTime(), nullable=True),
    sa.Column('actual_completion_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['assigned_to_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['completed_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_queue_app_id', 'queue_assignments', ['application_id'], unique=False)
    op.create_index('idx_queue_assigned_to_user', 'queue_assignments', ['assigned_to_user_id'], unique=False)
    op.create_index('idx_queue_name', 'queue_assignments', ['queue_name'], unique=False)
    op.create_index('idx_queue_status', 'queue_assignments', ['status'], unique=False)
    op.create_index(op.f('ix_queue_assignments_application_id'), 'queue_assignments', ['application_id'], unique=False)
    op.create_index(op.f('ix_queue_assignments_assigned_to_user_id'), 'queue_assignments', ['assigned_to_user_id'], unique=False)
    op.create_index(op.f('ix_queue_assignments_id'), 'queue_assignments', ['id'], unique=False)
    op.create_index(op.f('ix_queue_assignments_queue_name'), 'queue_assignments', ['queue_name'], unique=False)
    op.create_index(op.f('ix_queue_assignments_status'), 'queue_assignments', ['status'], unique=False)
    op.create_table('queue_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('from_queue', sa.String(length=100), nullable=True),
    sa.Column('to_queue', sa.String(length=100), nullable=True),
    sa.Column('moved_by_user_id', sa.Integer(), nullable=True),
    sa.Column('moved_at', sa.DateTime(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['moved_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_q_hist_application_id', 'queue_history', ['application_id'], unique=False)
    op.create_index(op.f('ix_queue_history_application_id'), 'queue_history', ['application_id'], unique=False)
    op.create_index(op.f('ix_queue_history_id'), 'queue_history', ['id'], unique=False)
    op.create_table('validation_errors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=True),
    sa.Column('error_type', sa.String(length=100), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_severity', sa.String(length=50), nullable=True),
    sa.Column('suggestion', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_val_err_application_id', 'validation_errors', ['application_id'], unique=False)
    op.create_index('idx_val_err_type', 'validation_errors', ['error_type'], unique=False)
    op.create_index(op.f('ix_validation_errors_application_id'), 'validation_errors', ['application_id'], unique=False)
    op.create_index(op.f('ix_validation_errors_error_type'), 'validation_errors', ['error_type'], unique=False)
    op.create_index(op.f('ix_validation_errors_id'), 'validation_errors', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_validation_errors_id'), table_name='validation_errors')
    op.drop_index(op.f('ix_validation_errors_error_type'), table_name='validation_errors')
    op.drop_index(op.f('ix_validation_errors_application_id'), table_name='validation_errors')
    op.drop_index('idx_val_err_type', table_name='validation_errors')
    op.drop_index('idx_val_err_application_id', table_name='validation_errors')
    op.drop_table('validation_errors')
    op.drop_index(op.f('ix_queue_history_id'), table_name='queue_history')
    op.drop_index(op.f('ix_queue_history_application_id'), table_name='queue_history')
    op.drop_index('idx_q_hist_application_id', table_name='queue_history')
    op.drop_table('queue_history')
    op.drop_index(op.f('ix_queue_assignments_status'), table_name='queue_assignments')
    op.drop_index(op.f('ix_queue_assignments_queue_name'), table_name='queue_assignments')
    op.drop_index(op.f('ix_queue_assignments_id'), table_name='queue_assignments')
    op.drop_index(op.f('ix_queue_assignments_assigned_to_user_id'), table_name='queue_assignments')
    op.drop_index(op.f('ix_queue_assignments_application_id'), table_name='queue_assignments')
    op.drop_index('idx_queue_status', table_name='queue_assignments')
    op.drop_index('idx_queue_name', table_name='queue_assignments')
    op.drop_index('idx_queue_assigned_to_user', table_name='queue_assignments')
    op.drop_index('idx_queue_app_id', table_name='queue_assignments')
    op.drop_table('queue_assignments')
    op.drop_index(op.f('ix_fraud_indicators_id'), table_name='fraud_indicators')
    op.drop_index(op.f('ix_fraud_indicators_application_id'), table_name='fraud_indicators')
    op.drop_index('idx_fraud_risk_level', table_name='fraud_indicators')
    op.drop_index('idx_fraud_application_id', table_name='fraud_indicators')
    op.drop_table('fraud_indicators')
    op.drop_index(op.f('ix_audit_log_user_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_timestamp'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_application_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_action'), table_name='audit_log')
    op.drop_index('idx_audit_user_id', table_name='audit_log')
    op.drop_index('idx_audit_timestamp', table_name='audit_log')
    op.drop_index('idx_audit_application_id', table_name='audit_log')
    op.drop_index('idx_audit_action', table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_application_documents_id'), table_name='application_documents')
    op.drop_index(op.f('ix_application_documents_application_id'), table_name='application_documents')
    op.drop_index('idx_doc_application_id', table_name='application_documents')
    op.drop_table('application_documents')
    op.drop_index(op.f('ix_user_sessions_user_id'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_id'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_access_token'), table_name='user_sessions')
    op.drop_index('idx_user_id', table_name='user_sessions')
    op.drop_index('idx_access_token', table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_index(op.f('ix_configuration_key'), table_name='configuration')
    op.drop_index(op.f('ix_configuration_id'), table_name='configuration')
    op.drop_index('idx_config_key', table_name='configuration')
    op.drop_table('configuration')
    op.drop_index(op.f('ix_applications_submitted_at'), table_name='applications')
    op.drop_index(op.f('ix_applications_status'), table_name='applications')
    op.drop_index(op.f('ix_applications_quality_score'), table_name='applications')
    op.drop_index(op.f('ix_applications_permit_type'), table_name='applications')
    op.drop_index(op.f('ix_applications_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_city'), table_name='applications')
    op.drop_index(op.f('ix_applications_citizen_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_assigned_to_user_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_application_id'), table_name='applications')
    op.drop_index('idx_submitted_at', table_name='applications')
    op.drop_index('idx_status', table_name='applications')
    op.drop_index('idx_quality_score', table_name='applications')
    op.drop_index('idx_permit_type', table_name='applications')
    op.drop_index('idx_created_at', table_name='applications')
    op.drop_index('idx_city', table_name='applications')
    op.drop_index('idx_citizen_id', table_name='applications')
    op.drop_index('idx_assigned_to', table_name='applications')
    op.drop_index('idx_application_id', table_name='applications')
    op.drop_table('applications')
    op.drop_index(op.f('ix_api_activity_log_user_id'), table_name='api_activity_log')
    op.drop_index(op.f('ix_api_activity_log_timestamp'), table_name='api_activity_log')
    op.drop_index(op.f('ix_api_activity_log_id'), table_name='api_activity_log')
    op.drop_index(op.f('ix_api_activity_log_endpoint'), table_name='api_activity_log')
    op.drop_index('idx_api_act_user_id', table_name='api_activity_log')
    op.drop_index('idx_api_act_timestamp', table_name='api_activity_log')
    op.drop_index('idx_api_act_endpoint', table_name='api_activity_log')
    op.drop_table('api_activity_log')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index('idx_username', table_name='users')
    op.drop_index('idx_role', table_name='users')
    op.drop_index('idx_email', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
