"""add_permit_number_to_applications

Revision ID: c32e9e9a19ae
Revises: f2c27e328993
Create Date: 2026-05-28 02:09:35.313916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c32e9e9a19ae'
down_revision: Union[str, None] = 'f2c27e328993'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('permit_number', sa.String(length=100), nullable=True))
    op.create_index('idx_permit_number', 'applications', ['permit_number'], unique=False)
    op.create_index(op.f('ix_applications_permit_number'), 'applications', ['permit_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_applications_permit_number'), table_name='applications')
    op.drop_index('idx_permit_number', table_name='applications')
    op.drop_column('applications', 'permit_number')
    # ### end Alembic commands ###
