"""add_approval_conditions

Revision ID: c5ce06fa0a61
Revises: c32e9e9a19ae
Create Date: 2026-05-28 02:18:41.795608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5ce06fa0a61'
down_revision: Union[str, None] = 'c32e9e9a19ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('approval_conditions', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'approval_conditions')
    # ### end Alembic commands ###
