"""add_notifications_and_user_preferences

Revision ID: f2c27e328993
Revises: a0c4066e937f
Create Date: 2026-05-28 02:08:53.890633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2c27e328993'
down_revision: Union[str, None] = 'a0c4066e937f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('in_app_notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.String(length=50), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('notification_type', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_notification_app_id', 'in_app_notifications', ['application_id'], unique=False)
    op.create_index('idx_notification_is_read', 'in_app_notifications', ['is_read'], unique=False)
    op.create_index('idx_notification_user_id', 'in_app_notifications', ['user_id'], unique=False)
    op.create_index(op.f('ix_in_app_notifications_application_id'), 'in_app_notifications', ['application_id'], unique=False)
    op.create_index(op.f('ix_in_app_notifications_created_at'), 'in_app_notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_in_app_notifications_id'), 'in_app_notifications', ['id'], unique=False)
    op.create_index(op.f('ix_in_app_notifications_is_read'), 'in_app_notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_in_app_notifications_user_id'), 'in_app_notifications', ['user_id'], unique=False)
    op.add_column('users', sa.Column('notification_preferences', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'notification_preferences')
    op.drop_index(op.f('ix_in_app_notifications_user_id'), table_name='in_app_notifications')
    op.drop_index(op.f('ix_in_app_notifications_is_read'), table_name='in_app_notifications')
    op.drop_index(op.f('ix_in_app_notifications_id'), table_name='in_app_notifications')
    op.drop_index(op.f('ix_in_app_notifications_created_at'), table_name='in_app_notifications')
    op.drop_index(op.f('ix_in_app_notifications_application_id'), table_name='in_app_notifications')
    op.drop_index('idx_notification_user_id', table_name='in_app_notifications')
    op.drop_index('idx_notification_is_read', table_name='in_app_notifications')
    op.drop_index('idx_notification_app_id', table_name='in_app_notifications')
    op.drop_table('in_app_notifications')
    # ### end Alembic commands ###
